<?php

namespace Database\Seeders;

use App\Models\Module;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $modules = [
            // Core Modules
            [
                'name' => 'Settings',
                'slug' => 'settings',
                'code' => 'SET',
                'description' => 'Organization settings and configuration',
                'icon' => 'cog',
                'version' => '1.0.0',
                'category' => 'Core',
                'display_order' => 1,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => true,
                'is_active' => true,
                'requires_license' => false,
            ],
            [
                'name' => 'Notifications',
                'slug' => 'notify',
                'code' => 'NTF',
                'description' => 'System-wide notification center',
                'icon' => 'bell',
                'version' => '1.0.0',
                'category' => 'Core',
                'display_order' => 2,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => true,
                'is_active' => true,
                'requires_license' => false,
            ],
            [
                'name' => 'Discuss',
                'slug' => 'discuss',
                'code' => 'DIS',
                'description' => 'Internal messaging and communication',
                'icon' => 'comments',
                'version' => '1.0.0',
                'category' => 'Core',
                'display_order' => 3,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => true,
                'is_active' => true,
                'requires_license' => false,
            ],
            [
                'name' => 'Contacts',
                'slug' => 'contacts',
                'code' => 'CON',
                'description' => 'Manage contacts, customers, and vendors',
                'icon' => 'address-book',
                'version' => '1.0.0',
                'category' => 'Core',
                'display_order' => 4,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => true,
                'is_active' => true,
                'requires_license' => false,
            ],
            [
                'name' => 'Calendar',
                'slug' => 'calendar',
                'code' => 'CAL',
                'description' => 'Schedule meetings and manage calendar',
                'icon' => 'calendar',
                'version' => '1.0.0',
                'category' => 'Productivity',
                'display_order' => 5,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => false,
            ],
            [
                'name' => 'Notes',
                'slug' => 'notes',
                'code' => 'NOT',
                'description' => 'Create and organize notes',
                'icon' => 'sticky-note',
                'version' => '1.0.0',
                'category' => 'Productivity',
                'display_order' => 6,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => false,
            ],
            [
                'name' => 'To-Do',
                'slug' => 'todo',
                'code' => 'TODO',
                'description' => 'Task management and to-do lists',
                'icon' => 'check-square',
                'version' => '1.0.0',
                'category' => 'Productivity',
                'display_order' => 7,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => false,
            ],

            // Finance & Accounting Modules
            [
                'name' => 'Accounting',
                'slug' => 'accounting',
                'code' => 'ACC',
                'description' => 'General ledger, journal entries, and financial reporting',
                'icon' => 'calculator',
                'version' => '1.0.0',
                'category' => 'Finance',
                'display_order' => 10,
                'dependencies' => ['contacts'],
                'metadata' => ['chart_of_accounts' => true],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Invoicing',
                'slug' => 'invoicing',
                'code' => 'INV',
                'description' => 'Create and send customer invoices',
                'icon' => 'file-invoice',
                'version' => '1.0.0',
                'category' => 'Finance',
                'display_order' => 11,
                'dependencies' => ['contacts'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Expenses',
                'slug' => 'expenses',
                'code' => 'EXP',
                'description' => 'Employee expense management and reimbursement',
                'icon' => 'receipt',
                'version' => '1.0.0',
                'category' => 'Finance',
                'display_order' => 12,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Documents',
                'slug' => 'documents',
                'code' => 'DOC',
                'description' => 'Document management system',
                'icon' => 'folder',
                'version' => '1.0.0',
                'category' => 'Productivity',
                'display_order' => 13,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Sign',
                'slug' => 'sign',
                'code' => 'SGN',
                'description' => 'Electronic signature and document signing',
                'icon' => 'signature',
                'version' => '1.0.0',
                'category' => 'Productivity',
                'display_order' => 14,
                'dependencies' => ['documents'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],

            // Sales & CRM Modules
            [
                'name' => 'CRM',
                'slug' => 'crm',
                'code' => 'CRM',
                'description' => 'Customer relationship management and pipeline',
                'icon' => 'users-cog',
                'version' => '1.0.0',
                'category' => 'Sales',
                'display_order' => 20,
                'dependencies' => ['contacts'],
                'metadata' => ['max_contacts' => null],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Sales',
                'slug' => 'sales',
                'code' => 'SAL',
                'description' => 'Sales orders and quotations',
                'icon' => 'shopping-cart',
                'version' => '1.0.0',
                'category' => 'Sales',
                'display_order' => 21,
                'dependencies' => ['contacts'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Point of Sale',
                'slug' => 'pos',
                'code' => 'POS',
                'description' => 'Retail point of sale system',
                'icon' => 'cash-register',
                'version' => '1.0.0',
                'category' => 'Sales',
                'display_order' => 22,
                'dependencies' => ['sales'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Subscriptions',
                'slug' => 'subscriptions',
                'code' => 'SUB',
                'description' => 'Recurring billing and subscription management',
                'icon' => 'sync',
                'version' => '1.0.0',
                'category' => 'Sales',
                'display_order' => 23,
                'dependencies' => ['sales'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Rental',
                'slug' => 'rental',
                'code' => 'RNT',
                'description' => 'Equipment and asset rental management',
                'icon' => 'key',
                'version' => '1.0.0',
                'category' => 'Sales',
                'display_order' => 24,
                'dependencies' => ['sales'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],

            // Website & E-Commerce Modules
            [
                'name' => 'Website Builder',
                'slug' => 'website',
                'code' => 'WEB',
                'description' => 'Build and manage your website',
                'icon' => 'globe',
                'version' => '1.0.0',
                'category' => 'Website',
                'display_order' => 30,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'E-Commerce',
                'slug' => 'ecommerce',
                'code' => 'ECM',
                'description' => 'Online store and shopping cart',
                'icon' => 'store',
                'version' => '1.0.0',
                'category' => 'Website',
                'display_order' => 31,
                'dependencies' => ['website', 'sales'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Blog',
                'slug' => 'blog',
                'code' => 'BLG',
                'description' => 'Blogging and content management',
                'icon' => 'blog',
                'version' => '1.0.0',
                'category' => 'Website',
                'display_order' => 32,
                'dependencies' => ['website'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Live Chat',
                'slug' => 'livechat',
                'code' => 'LVC',
                'description' => 'Live chat support for website visitors',
                'icon' => 'comment-dots',
                'version' => '1.0.0',
                'category' => 'Website',
                'display_order' => 33,
                'dependencies' => ['website'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Forum',
                'slug' => 'forum',
                'code' => 'FRM',
                'description' => 'Community forum and discussion boards',
                'icon' => 'comments',
                'version' => '1.0.0',
                'category' => 'Website',
                'display_order' => 34,
                'dependencies' => ['website'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'eLearning',
                'slug' => 'elearning',
                'code' => 'ELN',
                'description' => 'Online courses and training platform',
                'icon' => 'graduation-cap',
                'version' => '1.0.0',
                'category' => 'Website',
                'display_order' => 35,
                'dependencies' => ['website'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],

            // Inventory & Supply Chain Modules
            [
                'name' => 'Inventory',
                'slug' => 'inventory',
                'code' => 'STC',
                'description' => 'Warehouse and inventory management',
                'icon' => 'box',
                'version' => '1.0.0',
                'category' => 'Inventory',
                'display_order' => 40,
                'dependencies' => [],
                'metadata' => ['max_items' => null, 'max_warehouses' => 5],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Purchase',
                'slug' => 'purchase',
                'code' => 'PUR',
                'description' => 'Purchase orders and vendor management',
                'icon' => 'shopping-bag',
                'version' => '1.0.0',
                'category' => 'Inventory',
                'display_order' => 41,
                'dependencies' => ['inventory', 'contacts'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Manufacturing',
                'slug' => 'manufacturing',
                'code' => 'MFG',
                'description' => 'Manufacturing orders and bill of materials',
                'icon' => 'industry',
                'version' => '1.0.0',
                'category' => 'Manufacturing',
                'display_order' => 42,
                'dependencies' => ['inventory'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'PLM',
                'slug' => 'plm',
                'code' => 'PLM',
                'description' => 'Product lifecycle management',
                'icon' => 'project-diagram',
                'version' => '1.0.0',
                'category' => 'Manufacturing',
                'display_order' => 43,
                'dependencies' => ['manufacturing'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Maintenance',
                'slug' => 'maintenance',
                'code' => 'MNT',
                'description' => 'Equipment maintenance management',
                'icon' => 'tools',
                'version' => '1.0.0',
                'category' => 'Manufacturing',
                'display_order' => 44,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Quality',
                'slug' => 'quality',
                'code' => 'QLY',
                'description' => 'Quality control and assurance',
                'icon' => 'check-circle',
                'version' => '1.0.0',
                'category' => 'Manufacturing',
                'display_order' => 45,
                'dependencies' => ['inventory'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],

            // HR Modules
            [
                'name' => 'Employees',
                'slug' => 'employees',
                'code' => 'EMP',
                'description' => 'Employee directory and management',
                'icon' => 'user-tie',
                'version' => '1.0.0',
                'category' => 'HR',
                'display_order' => 50,
                'dependencies' => [],
                'metadata' => ['max_employees' => null],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Recruitment',
                'slug' => 'recruitment',
                'code' => 'REC',
                'description' => 'Applicant tracking and recruitment',
                'icon' => 'user-plus',
                'version' => '1.0.0',
                'category' => 'HR',
                'display_order' => 51,
                'dependencies' => ['employees'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Time Off',
                'slug' => 'leave',
                'code' => 'LVE',
                'description' => 'Leave and time-off management',
                'icon' => 'umbrella-beach',
                'version' => '1.0.0',
                'category' => 'HR',
                'display_order' => 52,
                'dependencies' => ['employees'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Appraisals',
                'slug' => 'appraisals',
                'code' => 'APR',
                'description' => 'Employee performance appraisals',
                'icon' => 'star',
                'version' => '1.0.0',
                'category' => 'HR',
                'display_order' => 53,
                'dependencies' => ['employees'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Referrals',
                'slug' => 'referrals',
                'code' => 'REF',
                'description' => 'Employee referral program',
                'icon' => 'handshake',
                'version' => '1.0.0',
                'category' => 'HR',
                'display_order' => 54,
                'dependencies' => ['employees', 'recruitment'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Fleet',
                'slug' => 'fleet',
                'code' => 'FLT',
                'description' => 'Company vehicle fleet management',
                'icon' => 'car',
                'version' => '1.0.0',
                'category' => 'HR',
                'display_order' => 55,
                'dependencies' => ['employees'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Payroll',
                'slug' => 'payroll',
                'code' => 'PAY',
                'description' => 'Payroll processing and management',
                'icon' => 'money-bill',
                'version' => '1.0.0',
                'category' => 'HR',
                'display_order' => 56,
                'dependencies' => ['employees', 'accounting'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Attendances',
                'slug' => 'attendances',
                'code' => 'ATT',
                'description' => 'Track employee attendance',
                'icon' => 'clock',
                'version' => '1.0.0',
                'category' => 'HR',
                'display_order' => 57,
                'dependencies' => ['employees'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],

            // Project Management Modules
            [
                'name' => 'Project',
                'slug' => 'project',
                'code' => 'PRJ',
                'description' => 'Project management and task tracking',
                'icon' => 'tasks',
                'version' => '1.0.0',
                'category' => 'Services',
                'display_order' => 60,
                'dependencies' => [],
                'metadata' => ['max_projects' => null],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Timesheets',
                'slug' => 'timesheets',
                'code' => 'TSH',
                'description' => 'Track time on projects and tasks',
                'icon' => 'stopwatch',
                'version' => '1.0.0',
                'category' => 'Services',
                'display_order' => 61,
                'dependencies' => ['project'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Field Service',
                'slug' => 'field',
                'code' => 'FSM',
                'description' => 'Field service management',
                'icon' => 'map-marked-alt',
                'version' => '1.0.0',
                'category' => 'Services',
                'display_order' => 62,
                'dependencies' => ['project'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Helpdesk',
                'slug' => 'helpdesk',
                'code' => 'HLP',
                'description' => 'Customer support ticketing system',
                'icon' => 'headset',
                'version' => '1.0.0',
                'category' => 'Services',
                'display_order' => 63,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Planning',
                'slug' => 'planning',
                'code' => 'PLN',
                'description' => 'Resource planning and scheduling',
                'icon' => 'calendar-alt',
                'version' => '1.0.0',
                'category' => 'Services',
                'display_order' => 64,
                'dependencies' => ['project'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Appointments',
                'slug' => 'appointments',
                'code' => 'APT',
                'description' => 'Online appointment booking',
                'icon' => 'calendar-check',
                'version' => '1.0.0',
                'category' => 'Services',
                'display_order' => 65,
                'dependencies' => ['calendar'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],

            // Marketing Modules
            [
                'name' => 'Email Marketing',
                'slug' => 'email',
                'code' => 'EML',
                'description' => 'Email campaigns and automation',
                'icon' => 'envelope',
                'version' => '1.0.0',
                'category' => 'Marketing',
                'display_order' => 70,
                'dependencies' => ['contacts'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'SMS Marketing',
                'slug' => 'sms',
                'code' => 'SMS',
                'description' => 'SMS campaign management',
                'icon' => 'sms',
                'version' => '1.0.0',
                'category' => 'Marketing',
                'display_order' => 71,
                'dependencies' => ['contacts'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Marketing Automation',
                'slug' => 'automation',
                'code' => 'MKA',
                'description' => 'Marketing automation workflows',
                'icon' => 'robot',
                'version' => '1.0.0',
                'category' => 'Marketing',
                'display_order' => 72,
                'dependencies' => ['email'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Events',
                'slug' => 'events',
                'code' => 'EVT',
                'description' => 'Event organization and ticketing',
                'icon' => 'ticket-alt',
                'version' => '1.0.0',
                'category' => 'Marketing',
                'display_order' => 73,
                'dependencies' => ['website'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Social Marketing',
                'slug' => 'social',
                'code' => 'SOC',
                'description' => 'Social media marketing and posting',
                'icon' => 'share-alt',
                'version' => '1.0.0',
                'category' => 'Marketing',
                'display_order' => 74,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Surveys',
                'slug' => 'surveys',
                'code' => 'SRV',
                'description' => 'Create and analyze surveys',
                'icon' => 'poll',
                'version' => '1.0.0',
                'category' => 'Marketing',
                'display_order' => 75,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],

            // Business Intelligence & Reporting
            [
                'name' => 'Dashboards',
                'slug' => 'dashboards',
                'code' => 'DSH',
                'description' => 'Custom dashboards and KPIs',
                'icon' => 'chart-line',
                'version' => '1.0.0',
                'category' => 'Reporting',
                'display_order' => 80,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Spreadsheet',
                'slug' => 'spreadsheet',
                'code' => 'SPD',
                'description' => 'Spreadsheet for data analysis',
                'icon' => 'table',
                'version' => '1.0.0',
                'category' => 'Reporting',
                'display_order' => 81,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Data Cleaning',
                'slug' => 'dataclean',
                'code' => 'DCL',
                'description' => 'Data quality and cleaning tools',
                'icon' => 'broom',
                'version' => '1.0.0',
                'category' => 'Reporting',
                'display_order' => 82,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],

            // Customization & Integration
            [
                'name' => 'Audit Logs',
                'slug' => 'audit',
                'code' => 'AUD',
                'description' => 'Compliance and activity tracking',
                'icon' => 'history',
                'version' => '1.0.0',
                'category' => 'Core',
                'display_order' => 88,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => true,
                'is_active' => true,
                'requires_license' => false,
            ],
            [
                'name' => 'Data Import/Export',
                'slug' => 'import',
                'code' => 'IMP',
                'description' => 'Bulk data import and export',
                'icon' => 'file-import',
                'version' => '1.0.0',
                'category' => 'Core',
                'display_order' => 89,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => true,
                'is_active' => true,
                'requires_license' => false,
            ],
            [
                'name' => 'Studio',
                'slug' => 'studio',
                'code' => 'STD',
                'description' => 'No-code customization platform',
                'icon' => 'paint-brush',
                'version' => '1.0.0',
                'category' => 'Customization',
                'display_order' => 90,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Approvals',
                'slug' => 'approvals',
                'code' => 'APV',
                'description' => 'Workflow approval rules',
                'icon' => 'check-double',
                'version' => '1.0.0',
                'category' => 'Customization',
                'display_order' => 91,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'IoT',
                'slug' => 'iot',
                'code' => 'IOT',
                'description' => 'Internet of Things integration',
                'icon' => 'wifi',
                'version' => '1.0.0',
                'category' => 'Integration',
                'display_order' => 92,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'VoIP',
                'slug' => 'voip',
                'code' => 'VIP',
                'description' => 'Voice over IP integration',
                'icon' => 'phone',
                'version' => '1.0.0',
                'category' => 'Integration',
                'display_order' => 93,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Knowledge',
                'slug' => 'knowledge',
                'code' => 'KNW',
                'description' => 'Knowledge base and wiki',
                'icon' => 'book',
                'version' => '1.0.0',
                'category' => 'Productivity',
                'display_order' => 94,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Barcode',
                'slug' => 'barcode',
                'code' => 'BAR',
                'description' => 'Barcode scanning and printing',
                'icon' => 'barcode',
                'version' => '1.0.0',
                'category' => 'Integration',
                'display_order' => 95,
                'dependencies' => ['inventory'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Webhooks',
                'slug' => 'webhooks',
                'code' => 'WHK',
                'description' => 'Webhook automation and integration',
                'icon' => 'plug',
                'version' => '1.0.0',
                'category' => 'Integration',
                'display_order' => 96,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'API Management',
                'slug' => 'api',
                'code' => 'API',
                'description' => 'API key and rate limiting management',
                'icon' => 'key',
                'version' => '1.0.0',
                'category' => 'Integration',
                'display_order' => 97,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => true,
                'is_active' => true,
                'requires_license' => false,
            ],
            [
                'name' => 'Reports Builder',
                'slug' => 'reports',
                'code' => 'RPT',
                'description' => 'Custom report designer',
                'icon' => 'file-alt',
                'version' => '1.0.0',
                'category' => 'Reporting',
                'display_order' => 98,
                'dependencies' => [],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],

            // Industry-Specific Modules
            [
                'name' => 'Restaurant',
                'slug' => 'restaurant',
                'code' => 'RST',
                'description' => 'Restaurant management system',
                'icon' => 'utensils',
                'version' => '1.0.0',
                'category' => 'Industry',
                'display_order' => 100,
                'dependencies' => ['pos'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
            [
                'name' => 'Consolidation',
                'slug' => 'consolidation',
                'code' => 'CNS',
                'description' => 'Multi-company financial consolidation',
                'icon' => 'chart-area',
                'version' => '1.0.0',
                'category' => 'Finance',
                'display_order' => 101,
                'dependencies' => ['accounting'],
                'metadata' => [],
                'is_core' => false,
                'is_active' => true,
                'requires_license' => true,
            ],
        ];

        foreach ($modules as $module) {
            Module::create($module);
        }
    }
}
