name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected!
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  
  - type: dropdown
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you using?
      options:
        - 8.2
        - 8.3
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: laravel-version
    attributes:
      label: Laravel Version
      description: What version of Laravel are you using?
      options:
        - 12.x
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: database
    attributes:
      label: Database
      description: Which database are you using?
      options:
        - MySQL
        - PostgreSQL
        - SQLite
        - Other
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
